tunnel: 01520cf3-fd88-4da8-9286-e5bf698b81c4
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: map.gpstraccar.xyz
    service: https://map-backend.onrender.com

  - hostname: admin.gpstraccar.xyz
    service: https://admin-backend.onrender.com

  - service: http_status:404
